Version 1.0.4 of IBM Federated Learning library
IBM/federated-learning-lib pull request #55
Opened 2021-03-02 03:36 UTC by shashank215r

### Changes
* Added multiple bias mitigation methods for training fairer FL models.
* Bug fixes in Tensorflow 2.1 Model wrapper.
* No API changes.
* No breaking changes.
### New Functionality
* Support Bias Mitigation methods.
   - Local Reweighing 
   - Global Reweighing with Differential Privacy
   - Federated Prejudice Removal 
* New Algorithm: FedProx

2021-03-02 21:11 UTC, Yi-Zoey approved these changes
Thanks for the update!

2021-03-02 22:17 UTC, Nathalie-B requested changes
Hi @shashank215r Thanks for the PR. Just one change requested. Thanks

2021-03-02 22:17 UTC, Nathalie-B commented on README.md
> +|Logistic Regression | Federated Prejudice Removal [Abay et al.](https://arxiv.org/abs/2012.02447) |
Why is this listed by model? They are applicable for all model types. Can you pls update? 

Also, we are missing: FedProx: [Tian Li et al.](https://arxiv.org/pdf/1812.06127.pdf).

2021-03-03 00:10 UTC, Nathalie-B approved these changes
Thanks, I made a minor edit. I think we are ready to go 👍

2021-03-03 00:12 UTC, merged